# Generated by Django 5.0.6 on 2024-06-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الطول')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الوزن')),
                ('hair_color', models.CharField(max_length=50, verbose_name='لون الشعر')),
                ('eye_color', models.CharField(max_length=50, verbose_name='لون العينين')),
                ('distinguishing_marks', models.TextField(blank=True, null=True, verbose_name='علامات مميزة')),
                ('last_seen_date', models.DateField(verbose_name='تاريخ آخر مرة شوهد فيها')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('health_conditions', models.TextField(blank=True, null=True, verbose_name='الحالة الصحية')),
                ('medications_needed', models.TextField(blank=True, null=True, verbose_name='الأدوية المطلوبة')),
                ('last_seen_clothing', models.TextField(blank=True, null=True, verbose_name='الملابس عند الاختفاء')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='صورة حديثة')),
                ('emergency_contact_info', models.TextField(blank=True, null=True, verbose_name='معلومات الاتصال في حالات الطوارئ')),
                ('status', models.CharField(choices=[('0', 'في انتظار'), ('1', 'مفقود'), ('2', 'تم العثور')], default=1, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('relationship_to_missing', models.CharField(max_length=100, verbose_name='العلاقة بالمفقود')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(max_length=200, verbose_name='عنوان السكن')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البلاغ')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('missing_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.missingperson', verbose_name='المفقود')),
            ],
        ),
    ]
