# Generated by Django 5.0.6 on 2024-06-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='emergency_contact_info',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='medications_needed',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='email',
        ),
    ]
