# Generated by Django 5.0.6 on 2024-06-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_missingperson_emergency_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اسم العائلة')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.CharField(max_length=200, verbose_name='عنوان السكن')),
                ('status', models.CharField(choices=[('تم العثور', 'تم العثور'), ('شوهد', 'شوهد')], max_length=20)),
                ('status_of_report', models.IntegerField(default=0)),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('there_is_loc', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.missingperson')),
            ],
        ),
    ]
