# Generated by Django 5.0.6 on 2024-06-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_reportinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='last_seen_date',
            field=models.DateTimeField(verbose_name='تاريخ آخر مرة شوهد فيها'),
        ),
        migrations.AlterField(
            model_name='reportinformation',
            name='status',
            field=models.CharField(choices=[('تم العثور', 'تم العثور'), ('شوهد', 'شوهد')], max_length=20, verbose_name='الحالة'),
        ),
    ]
