# Generated by Django 5.0.6 on 2024-07-03 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_reportinformation_missing_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='reportinformation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reportinformation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reportinformation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='reportinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
