# Generated by Django 5.0.6 on 2024-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_reporter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('0', 'في انتظار'), ('1', 'مفقود'), ('2', 'تم العثور'), ('3', 'رفض')], default=0, max_length=10),
        ),
    ]
