# Generated by Django 5.0.6 on 2024-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_alter_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpersondetails',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='foundpersondetails',
            name='current_health_status',
            field=models.CharField(max_length=150, verbose_name='الحالة الصحية الحالية'),
        ),
    ]
