# Generated by Django 5.0.6 on 2024-07-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_sendingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='Region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
