# Generated by Django 5.0.6 on 2024-08-05 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_missingperson_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='eye_color',
            field=models.CharField(max_length=255, verbose_name='لون العينين'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='hair_color',
            field=models.CharField(max_length=255, verbose_name='لون الشعر'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='اسم العائلة'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('0', 'في انتظار'), ('1', 'مفقود'), ('2', 'تم العثور'), ('3', 'رفض')], default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
