# Generated by Django 5.0.6 on 2024-08-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_alter_missingperson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('0', 'في انتظار'), ('1', 'مفقود'), ('2', 'تم العثور'), ('3', 'رفض')], default=0, max_length=255),
        ),
    ]
